import { useEffect, useMemo, useState } from 'react';
import type { AgriculturalProductInspectionRecord, AgriculturalProductInspectionSummary, Language } from '../types';

type Props = { summary?: AgriculturalProductInspectionSummary; language: Language };
type SortKey = 'year' | 'category' | 'item' | 'inspected' | 'qualified' | 'unqualified' | 'passRate';
const source = 'https://data.taipei/dataset/detail?id=8ab917b0-1029-4003-b776-f169b4e561f1';
const sum = (records: AgriculturalProductInspectionRecord[], field: 'inspected' | 'qualified' | 'unqualified') => records.reduce((total, record) => total + (record[field] ?? 0), 0);
const rate = (qualified: number, inspected: number) => inspected ? (qualified / inspected) * 100 : null;
const format = (value: number | null) => value === null ? '—' : `${value.toLocaleString()}${Number.isInteger(value) ? '' : '%'}`;
const percent = (value: number | null) => value === null ? '—' : `${value.toFixed(1)}%`;

export function AgriculturalProductInspectionsModule({ summary, language }: Props) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<AgriculturalProductInspectionRecord[]>([]);
  const [year, setYear] = useState(''); const [category, setCategory] = useState(''); const [status, setStatus] = useState(''); const [query, setQuery] = useState('');
  const [sort, setSort] = useState<SortKey>('year'); const [descending, setDescending] = useState(true);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/agricultural-product-inspections/records.json`).then((response) => response.ok ? response.json() : []).then(setRecords).catch(() => setRecords([])); }, []);
  const years = useMemo(() => [...new Set(records.map((record) => record.rocYear).filter((value): value is number => value !== null))].sort((a, b) => b - a), [records]);
  const categories = useMemo(() => [...new Set(records.map((record) => record.category).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const filtered = useMemo(() => records.filter((record) => (!year || String(record.rocYear) === year) && (!category || record.category === category) && (status !== 'passed' || (record.unqualified ?? 0) === 0) && (status !== 'unqualified' || (record.unqualified ?? 0) > 0) && (!query.trim() || [record.item, record.category].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))), [category, query, records, status, year]);
  const totals = useMemo(() => ({ inspected: sum(filtered, 'inspected'), qualified: sum(filtered, 'qualified'), unqualified: sum(filtered, 'unqualified') }), [filtered]);
  const overallRate = rate(totals.qualified, totals.inspected);
  const annual = useMemo(() => years.map((rocYear) => { const rows = filtered.filter((record) => record.rocYear === rocYear); const inspected = sum(rows, 'inspected'); const qualified = sum(rows, 'qualified'); return { rocYear, inspected, qualified, unqualified: sum(rows, 'unqualified'), passRate: rate(qualified, inspected) }; }).filter((row) => row.inspected > 0).reverse(), [filtered, years]);
  const categoryRows = useMemo(() => categories.map((name) => { const rows = filtered.filter((record) => record.category === name); const inspected = sum(rows, 'inspected'); const qualified = sum(rows, 'qualified'); return { name, inspected, qualified, unqualified: sum(rows, 'unqualified'), passRate: rate(qualified, inspected) }; }).filter((row) => row.inspected > 0).sort((a, b) => b.inspected - a.inspected), [categories, filtered]);
  const maxAnnual = Math.max(1, ...annual.map((row) => row.inspected));
  const latest = annual.at(-1);
  const largestCategory = categoryRows[0];
  const meaningfulLowest = [...categoryRows].filter((row) => row.inspected >= 5 && row.passRate !== null).sort((a, b) => (a.passRate ?? 100) - (b.passRate ?? 100))[0];
  const sorted = useMemo(() => [...filtered].sort((a, b) => { const left = sort === 'passRate' ? rate(a.qualified ?? 0, a.inspected ?? 0) : a[sort === 'year' ? 'rocYear' : sort] ?? -Infinity; const right = sort === 'passRate' ? rate(b.qualified ?? 0, b.inspected ?? 0) : b[sort === 'year' ? 'rocYear' : sort] ?? -Infinity; const result = typeof left === 'string' && typeof right === 'string' ? left.localeCompare(right, 'zh-Hant') : Number(left) - Number(right); return descending ? -result : result; }), [descending, filtered, sort]);
  const label = (zhText: string, enText: string) => zh ? zhText : enText;
  const setSortKey = (key: SortKey) => { if (key === sort) setDescending((value) => !value); else { setSort(key); setDescending(key !== 'category' && key !== 'item'); } };
  if (!records.length) return <section className="agricultural-module"><p>{label('載入抽檢統計中…', 'Loading inspection statistics…')}</p></section>;
  return <section className="agricultural-module">
    <header className="module-header agricultural-header"><p>{label('食品與農產品', 'Food & agricultural products')}</p><h2>{label('農產品抽檢統計', 'Agricultural Product Inspections')}</h2><span>{label('臺北市政府標章農產品的年度統計；這是城市層級資料，並不對應特定商店或餐廳。', 'Annual Taipei government statistics for certified agricultural products. These city-level records are not connected to individual stores or restaurants.')}</span></header>
    <div className="agricultural-filters"><label>{label('年度', 'Year')}<select value={year} onChange={(event) => setYear(event.target.value)}><option value="">{label('全部', 'All')}</option>{years.map((value) => <option value={value} key={value}>{value} ({value + 1911})</option>)}</select></label><label>{label('類別', 'Category')}<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">{label('全部', 'All')}</option>{categories.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>{label('抽檢結果', 'Inspection status')}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{label('全部', 'All')}</option><option value="passed">{label('僅全數合格', 'Fully qualified only')}</option><option value="unqualified">{label('含不合格', 'With unqualified cases')}</option></select></label><label className="search-field">{label('項目搜尋', 'Item search')}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={label('搜尋項目或類別', 'Search item or category')} /></label></div>
    <div className="summary-grid agricultural-kpis">{[[label('抽驗總件數／場', 'Total inspections'), format(totals.inspected)], [label('合格件數／場', 'Qualified inspections'), format(totals.qualified)], [label('不合格件數／場', 'Unqualified inspections'), format(totals.unqualified)], [label('加權合格率', 'Weighted pass rate'), percent(overallRate)]].map(([name, value], index) => <article className={`summary-tile ${index === 2 ? 'agricultural-emphasis' : ''}`} key={name}><span>{name}</span><strong>{value}</strong></article>)}</div>
    {latest && <section className="agricultural-latest"><h3>{label(`最新年度摘要：${latest.rocYear} 年（${latest.rocYear + 1911}）`, `Latest year: ROC ${latest.rocYear} (${latest.rocYear + 1911})`)}</h3><p>{label(`抽驗 ${latest.inspected.toLocaleString()} 件／場，合格 ${latest.qualified.toLocaleString()}，不合格 ${latest.unqualified.toLocaleString()}，加權合格率 ${percent(latest.passRate)}。`, `${latest.inspected.toLocaleString()} inspections; ${latest.qualified.toLocaleString()} qualified; ${latest.unqualified.toLocaleString()} unqualified; weighted pass rate ${percent(latest.passRate)}.`)}</p></section>}
    <section className="chart-grid"><article><h3>{label('年度抽檢趨勢', 'Annual inspection trend')}</h3><div className="agricultural-bars">{annual.map((row) => <div className="agricultural-bar-row" key={row.rocYear}><span>{row.rocYear}<small>/{row.rocYear + 1911}</small></span><div><i className="agricultural-total" style={{ width: `${(row.inspected / maxAnnual) * 100}%` }} title={label('抽驗', 'Inspected')} /><i className="agricultural-qualified" style={{ width: `${(row.qualified / maxAnnual) * 100}%` }} title={label('合格', 'Qualified')} /><i className="agricultural-unqualified" style={{ width: `${Math.max(1, (row.unqualified / maxAnnual) * 100)}%` }} title={label('不合格', 'Unqualified')} /></div><b>{row.inspected}</b></div>)}</div><p className="chart-legend"><span>■ {label('抽驗', 'Inspected')}</span><span>■ {label('合格', 'Qualified')}</span><span>■ {label('不合格', 'Unqualified')}</span></p></article><article><h3>{label('合格率趨勢', 'Pass-rate trend')}</h3><div className="agricultural-rate-list">{annual.map((row) => <div key={row.rocYear}><span>{row.rocYear} ({row.rocYear + 1911})</span><strong>{percent(row.passRate)}</strong></div>)}</div></article></section>
    <section className="chart-grid"><article><h3>{label('類別分析', 'Category analysis')}</h3><div className="agricultural-rate-list">{categoryRows.map((row) => <div key={row.name}><span>{row.name} <small>({row.inspected})</small></span><strong>{percent(row.passRate)}</strong></div>)}</div></article><article><h3>{label('不合格項目', 'Unqualified product analysis')}</h3><div className="agricultural-rate-list">{sorted.filter((row) => (row.unqualified ?? 0) > 0).sort((a, b) => (b.unqualified ?? 0) - (a.unqualified ?? 0)).map((row) => <div key={row.id}><span>{row.item} · {row.category}</span><strong>{row.unqualified} / {format(rate(row.qualified ?? 0, row.inspected ?? 0))}</strong></div>) || <p>—</p>}</div></article></section>
    <section className="agricultural-insights"><h3>{label('資料洞察', 'Insights')}</h3><ul><li>{label(`目前篩選範圍共 ${totals.inspected.toLocaleString()} 件／場，整體加權合格率為 ${percent(overallRate)}。`, `${totals.inspected.toLocaleString()} inspections are in the current filter, with a weighted pass rate of ${percent(overallRate)}.`)}</li>{largestCategory && <li>{label(`${largestCategory.name} 是抽驗量最大的類別，共 ${largestCategory.inspected.toLocaleString()} 件／場。`, `${largestCategory.name} has the largest inspection count (${largestCategory.inspected.toLocaleString()}).`)}</li>}{meaningfulLowest && <li>{label(`在至少 5 件／場的類別中，${meaningfulLowest.name} 的合格率最低，為 ${percent(meaningfulLowest.passRate)}（${meaningfulLowest.inspected} 件／場）。`, `Among categories with at least five inspections, ${meaningfulLowest.name} has the lowest pass rate: ${percent(meaningfulLowest.passRate)} (${meaningfulLowest.inspected} inspections).`)}</li>}</ul></section>
    <section><h3>{label('詳細紀錄', 'Detailed records')}</h3><div className="green-store-table-wrap"><table className="green-store-table agricultural-table"><thead><tr>{([['year', label('年度', 'Year')], ['category', label('類別', 'Category')], ['item', label('項目', 'Item')], ['inspected', label('抽驗', 'Inspected')], ['qualified', label('合格', 'Qualified')], ['unqualified', label('不合格', 'Unqualified')], ['passRate', label('合格率', 'Pass rate')]] as Array<[SortKey, string]>).map(([key, name]) => <th key={key}><button className="table-sort" onClick={() => setSortKey(key)}>{name}{sort === key ? (descending ? ' ↓' : ' ↑') : ''}</button></th>)}</tr></thead><tbody>{sorted.map((row) => <tr key={row.id}><td>{row.rocYear === null ? '—' : `${row.rocYear} (${row.year})`}</td><td>{row.category || '—'}</td><td>{row.item || '—'}</td><td>{format(row.inspected)}</td><td>{format(row.qualified)}</td><td>{format(row.unqualified)}</td><td>{percent(rate(row.qualified ?? 0, row.inspected ?? 0))}</td></tr>)}</tbody></table></div></section>
    <footer className="data-notes"><h3>{label('資料來源與方法', 'Data source & method')}</h3><p>{label('資料來源：臺北市政府標章農產品抽檢清冊。彙總合格率以合格件數／場 ÷ 抽驗件數／場計算，不平均個別列的百分比。', 'Source: Taipei City Government Certified Agricultural Product Inspection List. Aggregate pass rates use qualified inspections ÷ total inspections, rather than an average of row percentages.')}</p><p><a href={source} target="_blank" rel="noopener noreferrer">{source}</a></p><p>{summary && label(`匯入 ${summary.importedRowCount} 筆；資料年度 ${summary.earliestRocYear}–${summary.latestRocYear}；來源更新 ${new Date(summary.sourceUpdatedAt).toLocaleDateString('zh-TW')}；本地更新 ${new Date(summary.generatedAt).toLocaleString('zh-TW')}。`, `${summary.importedRowCount} imported rows; ROC years ${summary.earliestRocYear}–${summary.latestRocYear}; source updated ${new Date(summary.sourceUpdatedAt).toLocaleDateString('en-CA')}; locally refreshed ${new Date(summary.generatedAt).toLocaleString('en-CA')}.`)}</p></footer>
  </section>;
}
