import { useEffect, useMemo, useState } from 'react';
import type { FailedFoodInspectionRecord, FailedFoodInspectionSummary, Language } from '../types';
import { DisclaimerNotice } from './DisclaimerNotice';

type Props = { summary?: FailedFoodInspectionSummary; language: Language };
type View = 'overview' | 'trends' | 'categories' | 'reasons' | 'districts' | 'records' | 'quality' | 'notes';
const path = `${import.meta.env.BASE_URL}data/failed-food-inspection-records/records.json`;
const source = 'https://data.taipei/dataset/detail?id=09a917a0-0fb5-47e1-957c-5f1268fba517';
const missing = (language: Language) => language === 'zh' ? '—' : '—';
const copy = (language: Language) => language === 'zh' ? {
  eyebrow: '食品安全、抽驗結果與不合格紀錄', title: '臺北市衛生局食品抽驗不合格清冊', intro: '依公開抽驗紀錄瀏覽資料；資料為特定日期、專案、樣品與批次的歷史結果。', overview: '總覽', trends: '年度趨勢', categories: '食品分類', reasons: '不符合規定原因', districts: '行政區分布', records: '抽驗紀錄', quality: '資料品質', notes: '資料說明',
  total: '不合格抽驗紀錄', latest: '最新抽驗日期', years: '涵蓋年度', categoryCount: '食品分類', samples: '不重複檢體名稱', districtCount: '行政區數', topReason: '最常見不符合原因', topCategory: '最常見食品分類', year: '抽驗年度', district: '行政區', category: '分類', project: '專案名稱', reason: '不符合規定原因', search: '搜尋', searchPlaceholder: '檢體、地點、專案、分類、結果或原因', all: '全部', result: '檢驗結果', location: '抽驗地點', sourceYear: '來源年度', date: '抽驗日期', sample: '檢體名稱', export: '下載篩選 CSV', previous: '上一頁', next: '下一頁', sort: '排序', results: '筆結果',
  byYear: '各年度不合格紀錄', byMonth: '各月份不合格紀錄', byCategory: '各食品分類紀錄', byReason: '各不符合規定原因紀錄', byDistrict: '各行政區紀錄', categoryYear: '各年度食品分類紀錄', invalidDates: '無效日期', duplicates: '重複列', missingLocations: '缺少抽驗地點', unknownCategories: '未知分類', unresolvedDistricts: '未解析行政區',
  interpretation: '這些紀錄描述特定抽驗日期與專案中的不合格食品樣品。它們不代表該地點、品牌或業者目前仍有相同問題，也不表示所有產品或批次都不合格。', disclaimer: '本資料為臺北市衛生局公開食品抽驗不合格紀錄。結果適用於特定日期、專案、樣品與批次，不代表即時營業狀態、目前衛生狀況、所有產品品質、持續不合格、法律責任或完整食品安全評價。最新案件與業者資訊請向臺北市政府衛生局及相關主管機關確認。', noCoordinates: '抽驗地點可能是店名、市場、地址、製造商、供應商或描述文字；本站不會將不完整地點自動地理編碼，也不建立精確地圖標記。外部地圖連結僅供文字查詢。',
} : {
  eyebrow: 'Food Safety, Inspection Results & Noncompliance Records', title: 'Failed Food Inspection Records', intro: 'Browse public inspection records. Each record is a historical result for a specific date, project, sample, and batch.', overview: 'Overview', trends: 'Annual Trends', categories: 'Food Categories', reasons: 'Noncompliance Reasons', districts: 'District Distribution', records: 'Inspection Records', quality: 'Data Quality', notes: 'Data Notes',
  total: 'Total failed inspection records', latest: 'Latest inspection date', years: 'Years covered', categoryCount: 'Food categories', samples: 'Unique sample names', districtCount: 'Districts represented', topReason: 'Most common noncompliance reason', topCategory: 'Most common food category', year: 'Inspection year', district: 'District', category: 'Category', project: 'Project', reason: 'Noncompliance reason', search: 'Search', searchPlaceholder: 'Sample, location, project, category, result, or reason', all: 'All', result: 'Inspection result', location: 'Inspection location', sourceYear: 'Source year', date: 'Inspection date', sample: 'Sample', export: 'Download filtered CSV', previous: 'Previous', next: 'Next', sort: 'Sort', results: 'results',
  byYear: 'Failed records by year', byMonth: 'Failed records by month', byCategory: 'Records by food category', byReason: 'Records by noncompliance reason', byDistrict: 'Records by district', categoryYear: 'Food categories by year', invalidDates: 'Invalid dates', duplicates: 'Duplicate rows', missingLocations: 'Missing locations', unknownCategories: 'Unknown categories', unresolvedDistricts: 'Unresolved districts',
  interpretation: 'These records describe failed food samples from specific inspection dates and projects. They do not establish that a location, brand, or business currently has the same issue or that all products or batches are noncompliant.', disclaimer: 'This dataset contains public records of failed food inspections conducted by the Taipei Department of Health. Results apply to specific dates, projects, samples, and batches and do not confirm current operating status, current hygiene conditions, the quality of all products, continuing noncompliance, legal responsibility, or complete food-safety quality. Verify current case and business information with Taipei City Department of Health and relevant authorities.', noCoordinates: 'Inspection location may be a store name, market, address, manufacturer, supplier, or descriptive text. This module does not geocode incomplete locations or create exact map markers. External map links are text lookup only.',
};
function Chart({ data }: { data: Array<{ label: string; value: number }> }) { const max = Math.max(1, ...data.map((v) => v.value)); return <div className="bar-chart">{data.map((v) => <div className="bar-row" key={v.label}><span title={v.label}>{v.label}</span><div className="bar-track"><div className="bar-fill inspection-fill" style={{ width: `${v.value / max * 100}%` }} /></div><strong>{v.value}</strong></div>)}</div>; }
const count = (values: string[]) => [...values.reduce((m, value) => m.set(value, (m.get(value) ?? 0) + 1), new Map<string, number>()).entries()].map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
export function FailedFoodInspectionModule({ summary, language }: Props) {
  const text = copy(language); const [records, setRecords] = useState<FailedFoodInspectionRecord[]>([]); const [view, setView] = useState<View>('overview'); const [year, setYear] = useState(''); const [district, setDistrict] = useState(''); const [category, setCategory] = useState(''); const [project, setProject] = useState(''); const [reason, setReason] = useState(''); const [query, setQuery] = useState(''); const [sort, setSort] = useState<'date-desc' | 'date-asc' | 'sample'>('date-desc'); const [page, setPage] = useState(0);
  useEffect(() => { fetch(path).then((r) => r.ok ? r.json() : []).then(setRecords).catch(() => setRecords([])); }, []);
  const options = useMemo(() => ({ years: [...new Set(records.map((r) => r.inspectionYear).filter((v): v is number => v !== null))].sort((a, b) => b - a), districts: [...new Set(records.map((r) => r.districtName).filter(Boolean))].sort(), categories: [...new Set(records.map((r) => r.category).filter(Boolean))].sort(), projects: [...new Set(records.map((r) => r.projectName).filter(Boolean))].sort(), reasons: [...new Set(records.map((r) => r.noncomplianceReason).filter(Boolean))].sort() }), [records]);
  const filtered = useMemo(() => records.filter((r) => { const needle = query.trim().toLocaleLowerCase(); return (!year || String(r.inspectionYear) === year) && (!district || r.districtName === district) && (!category || r.category === category) && (!project || r.projectName === project) && (!reason || r.noncomplianceReason === reason) && (!needle || [r.sampleName, r.inspectionLocation, r.projectName, r.category, r.inspectionResult, r.noncomplianceReason].join(' ').toLocaleLowerCase().includes(needle)); }).sort((a, b) => sort === 'sample' ? a.sampleName.localeCompare(b.sampleName, 'zh-Hant') : (a.inspectionDate ?? '').localeCompare(b.inspectionDate ?? '') * (sort === 'date-asc' ? 1 : -1)), [category, district, project, query, reason, records, sort, year]);
  const charts = useMemo(() => ({ year: count(filtered.flatMap((r) => r.inspectionYear ? [String(r.inspectionYear)] : [])), month: count(filtered.flatMap((r) => r.inspectionDate ? [r.inspectionDate.slice(0, 7)] : [])), category: count(filtered.flatMap((r) => r.category ? [r.category] : [])), reason: count(filtered.flatMap((r) => r.noncomplianceReason ? [r.noncomplianceReason] : [])), district: count(filtered.flatMap((r) => r.districtName ? [r.districtName] : [])), categoryYear: count(filtered.flatMap((r) => r.category && r.inspectionYear ? [`${r.inspectionYear} · ${r.category}`] : [])) }), [filtered]);
  const cards: Array<[string, string | number]> = [[text.total, filtered.length], [text.latest, filtered.map((r) => r.inspectionDate).filter((v): v is string => Boolean(v)).sort().at(-1) ?? missing(language)], [text.years, new Set(filtered.map((r) => r.inspectionYear).filter(Boolean)).size], [text.categoryCount, charts.category.length], [text.samples, new Set(filtered.map((r) => r.sampleName).filter(Boolean)).size], [text.districtCount, charts.district.length], [text.topReason, charts.reason[0]?.label ?? missing(language)], [text.topCategory, charts.category[0]?.label ?? missing(language)]];
  const download = () => { const headers = ['Inspection date', 'Project', 'Category', 'Sample', 'Inspection location', 'District', 'Inspection result', 'Noncompliance reason', 'Source year']; const csv = [headers, ...filtered.map((r) => [r.inspectionDateRaw, r.projectName, r.category, r.sampleName, r.inspectionLocation, r.districtName, r.inspectionResult, r.noncomplianceReason, r.sourceYear].map((v) => `"${String(v ?? '').replaceAll('"', '""')}"`))].map((row) => row.join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' })); a.download = 'failed-food-inspection-records-filtered.csv'; a.click(); URL.revokeObjectURL(a.href); };
  const tabs: Array<[View, string]> = [['overview', text.overview], ['trends', text.trends], ['categories', text.categories], ['reasons', text.reasons], ['districts', text.districts], ['records', text.records], ['quality', text.quality], ['notes', text.notes]]; const pageRows = filtered.slice(page * 50, page * 50 + 50); const quality = summary?.dataQuality;
  const filters = <div className="inspection-filters"><label>{text.year}<select value={year} onChange={(e) => { setYear(e.target.value); setPage(0); }}><option value="">{text.all}</option>{options.years.map((v) => <option key={v}>{v}</option>)}</select></label><label>{text.district}<select value={district} onChange={(e) => { setDistrict(e.target.value); setPage(0); }}><option value="">{text.all}</option>{options.districts.map((v) => <option key={v}>{v}</option>)}</select></label><label>{text.category}<select value={category} onChange={(e) => { setCategory(e.target.value); setPage(0); }}><option value="">{text.all}</option>{options.categories.map((v) => <option key={v}>{v}</option>)}</select></label><label>{text.project}<select value={project} onChange={(e) => { setProject(e.target.value); setPage(0); }}><option value="">{text.all}</option>{options.projects.map((v) => <option key={v}>{v}</option>)}</select></label><label>{text.reason}<select value={reason} onChange={(e) => { setReason(e.target.value); setPage(0); }}><option value="">{text.all}</option>{options.reasons.map((v) => <option key={v}>{v}</option>)}</select></label><label className="search-field">{text.search}<input value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder={text.searchPlaceholder} /></label></div>;
  return <section className="inspection-module"><header className="module-header inspection-header"><p>{text.eyebrow}</p><h2>{text.title}</h2><span>{text.intro}</span></header><DisclaimerNotice>{text.interpretation}</DisclaimerNotice><DisclaimerNotice>{text.disclaimer}</DisclaimerNotice><div className="green-store-tabs" role="tablist">{tabs.map(([id, label]) => <button type="button" role="tab" key={id} className={view === id ? 'active' : ''} aria-selected={view === id} onClick={() => setView(id)}>{label}</button>)}</div>{filters}
    {view === 'overview' && <div className="green-store-view"><div className="summary-grid">{cards.map(([label, value]) => <div className="summary-tile" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="chart-grid"><article><h3>{text.byYear}</h3><Chart data={charts.year} /></article><article><h3>{text.byCategory}</h3><Chart data={charts.category} /></article><article><h3>{text.byReason}</h3><Chart data={charts.reason} /></article></div></div>}
    {view === 'trends' && <div className="green-store-view chart-grid"><article><h3>{text.byYear}</h3><Chart data={charts.year} /></article><article><h3>{text.byMonth}</h3><Chart data={charts.month} /></article><article><h3>{text.categoryYear}</h3><Chart data={charts.categoryYear} /></article></div>}
    {view === 'categories' && <div className="green-store-view chart-grid"><article><h3>{text.byCategory}</h3><Chart data={charts.category} /></article></div>}{view === 'reasons' && <div className="green-store-view chart-grid"><article><h3>{text.byReason}</h3><Chart data={charts.reason} /></article></div>}{view === 'districts' && <div className="green-store-view chart-grid"><article><h3>{text.byDistrict}</h3><Chart data={charts.district} /></article></div>}
    {view === 'records' && <section className="green-store-view"><div className="inspection-actions"><label>{text.sort}<select value={sort} onChange={(e) => setSort(e.target.value as typeof sort)}><option value="date-desc">{text.date} ↓</option><option value="date-asc">{text.date} ↑</option><option value="sample">{text.sample}</option></select></label><button type="button" className="nearby-button" onClick={download}>{text.export}</button><span>{filtered.length} {text.results}</span></div><div className="green-store-table-wrap"><table className="green-store-table"><thead><tr>{[text.date, text.project, text.category, text.sample, text.location, text.district, text.result, text.reason, text.sourceYear].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{pageRows.map((r) => <tr key={r.id}><td>{r.inspectionDateRaw || missing(language)}</td><td>{r.projectName || missing(language)}</td><td>{r.category || missing(language)}</td><td>{r.sampleName || missing(language)}</td><td>{r.inspectionLocation || missing(language)}</td><td>{r.districtName || missing(language)}</td><td>{r.inspectionResult || missing(language)}</td><td>{r.noncomplianceReason || missing(language)}</td><td>{r.sourceYear ?? missing(language)}</td></tr>)}</tbody></table></div><div className="inspection-pagination"><button type="button" disabled={!page} onClick={() => setPage((p) => p - 1)}>{text.previous}</button><span>{page + 1} / {Math.max(1, Math.ceil(filtered.length / 50))}</span><button type="button" disabled={(page + 1) * 50 >= filtered.length} onClick={() => setPage((p) => p + 1)}>{text.next}</button></div></section>}
    {view === 'quality' && <section className="green-store-view"><div className="summary-grid">{[[text.invalidDates, quality?.invalidDateCount ?? 0], [text.duplicates, quality?.duplicateRowCount ?? 0], [text.missingLocations, quality?.missingLocationCount ?? 0], [text.unknownCategories, quality?.unknownCategoryCount ?? 0], [text.unresolvedDistricts, quality?.unresolvedDistrictCount ?? 0]].map(([label, value]) => <div className="summary-tile" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div></section>}
    {view === 'notes' && <section className="green-store-view data-notes"><h3>{text.title}</h3><p><a href={source} target="_blank" rel="noopener noreferrer">{source}</a></p><p>{text.noCoordinates}</p></section>}</section>;
}
