import { useEffect, useMemo, useState } from 'react';
import type { Language, RestaurantHygieneGradingRecord, RestaurantHygieneGradingSummary } from '../types';
import { DisclaimerNotice } from './DisclaimerNotice';

type Props = { summary?: RestaurantHygieneGradingSummary; language: Language };
type View = 'overview' | 'districts' | 'results' | 'directory' | 'quality' | 'notes';
const dataPath = `${import.meta.env.BASE_URL}data/restaurant-hygiene-grading-records/records.json`;
const source = 'https://data.taipei/dataset/detail?id=59579c19-a561-4564-8c0f-545bfb32c0f6';

const copy = (language: Language) => language === 'zh' ? {
  eyebrow: '餐飲業者、食品衛生與評核紀錄', title: '餐飲衛生管理分級評核業者', intro: '依行政區與來源公布的評核結果瀏覽公開紀錄。地址僅供外部地圖查詢，本站不建立精確地圖標記。',
  overview: '總覽', districts: '行政區分布', results: '評核結果', directory: '評核業者名錄', quality: '資料品質', notes: '資料說明',
  total: '評核紀錄總數', unique: '不重複業者', covered: '涵蓋行政區', categories: '評核結果類別', topDistrict: '紀錄最多行政區', registrations: '有登錄字號紀錄',
  search: '搜尋', searchPlaceholder: '業者名稱、登錄字號、行政區、地址或評核結果', allDistricts: '全部行政區', allResults: '全部評核結果', validAddress: '僅顯示有有效地址', resultsCount: '筆結果',
  business: '業者名稱', assessment: '評核結果', district: '行政區', address: '地址', registration: '食品業者登錄字號', map: '地圖查詢', noResults: '沒有符合目前篩選條件的紀錄。',
  districtChart: '各行政區評核紀錄', resultChart: '各評核結果紀錄', crossChart: '各行政區的評核結果', qualityTitle: '轉換與欄位完整性', duplicates: '略過重複紀錄', missingNames: '缺少業者名稱', missingRegistrations: '缺少登錄字號', missingAddresses: '缺少地址', missingAssessments: '缺少評核結果', unknownDistricts: '無法辨識行政區', unknownAssessments: '未知評核值',
  notesTitle: '使用資料前請注意', source: '資料來源', location: '位置資訊', noCoordinates: '資料提供地址，但沒有已確認的官方座標。本模組不會自動地理編碼，也不會建立精確地圖標記。', lookup: '地圖查詢連結會將業者名稱與地址交給外部地圖服務；請自行確認目的地與最新資訊。',
  disclaimer: '本資料為臺北市通過餐飲衛生管理分級評核業者公開紀錄，僅供食品衛生與公共資料查詢參考。評核結果為來源公布紀錄，不代表即時營業狀態、目前衛生狀況、完整食品安全評價、無違規保證、餐點品質、價格或官方推薦。最新評核與營業資訊請向業者或臺北市政府衛生局確認。',
} : {
  eyebrow: 'Food Businesses, Food Hygiene & Assessment Records', title: 'Food Business Hygiene Grading Records', intro: 'Browse source-published records by district and assessment result. Addresses are provided for external map lookup only; this module does not create exact map markers.',
  overview: 'Overview', districts: 'District Distribution', results: 'Assessment Results', directory: 'Evaluated Business Directory', quality: 'Data Quality', notes: 'Data Notes',
  total: 'Total assessment records', unique: 'Unique businesses', covered: 'Districts covered', categories: 'Assessment-result categories', topDistrict: 'District with most records', registrations: 'Records with registration numbers',
  search: 'Search', searchPlaceholder: 'Business name, registration number, district, address, or assessment result', allDistricts: 'All districts', allResults: 'All assessment results', validAddress: 'Only records with valid address', resultsCount: 'results',
  business: 'Business name', assessment: 'Assessment result', district: 'District', address: 'Address', registration: 'Registration number', map: 'Map lookup', noResults: 'No records match the current filters.',
  districtChart: 'Records by district', resultChart: 'Records by assessment result', crossChart: 'Assessment results by district', qualityTitle: 'Conversion and field completeness', duplicates: 'Skipped duplicate records', missingNames: 'Missing business names', missingRegistrations: 'Missing registration numbers', missingAddresses: 'Missing addresses', missingAssessments: 'Missing assessment results', unknownDistricts: 'Unknown districts', unknownAssessments: 'Unknown assessment values',
  notesTitle: 'Before using this data', source: 'Source', location: 'Location information', noCoordinates: 'This dataset provides addresses but no officially confirmed coordinates. This module does not automatically geocode records or create exact map markers.', lookup: 'External map links submit the business name and address to a mapping service. Please confirm the destination and current information yourself.',
  disclaimer: 'This dataset contains public hygiene-grading records for food businesses in Taipei. Assessment results are source-published records and do not confirm real-time operation, current hygiene conditions, complete food-safety quality, absence of violations, food quality, prices, or official recommendation. Verify current assessment and business information with the operator or Taipei City Department of Health.',
};

function BarChart({ data }: { data: Array<{ label: string; value: number }> }) {
  const max = Math.max(1, ...data.map((item) => item.value));
  return <div className="bar-chart">{data.map((item) => <div className="bar-row" key={item.label}><span title={item.label}>{item.label}</span><div className="bar-track"><div className="bar-fill hygiene-fill" style={{ width: `${item.value / max * 100}%` }} /></div><strong>{item.value}</strong></div>)}</div>;
}

export function RestaurantHygieneGradingModule({ summary, language }: Props) {
  const [records, setRecords] = useState<RestaurantHygieneGradingRecord[]>([]);
  const [view, setView] = useState<View>('overview');
  const [query, setQuery] = useState(''); const [district, setDistrict] = useState(''); const [assessment, setAssessment] = useState(''); const [validAddressOnly, setValidAddressOnly] = useState(false);
  const text = copy(language);
  useEffect(() => { fetch(dataPath).then((response) => response.ok ? response.json() : []).then(setRecords).catch(() => setRecords([])); }, []);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter((value): value is string => Boolean(value)))].sort(), [records]);
  const assessments = useMemo(() => [...new Set(records.map((record) => record.assessmentResult).filter(Boolean))].sort(), [records]);
  const districtData = useMemo(() => districts.map((label) => ({ label, value: records.filter((record) => record.districtName === label).length })).sort((a, b) => b.value - a.value), [districts, records]);
  const resultData = useMemo(() => assessments.map((label) => ({ label, value: records.filter((record) => record.assessmentResult === label).length })).sort((a, b) => b.value - a.value), [assessments, records]);
  const crossData = useMemo(() => districtData.flatMap(({ label: districtName }) => assessments.map((result) => ({ label: `${districtName} · ${result}`, value: records.filter((record) => record.districtName === districtName && record.assessmentResult === result).length })).filter((item) => item.value > 0)), [assessments, districtData, records]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return records.filter((record) => (!district || record.districtName === district) && (!assessment || record.assessmentResult === assessment) && (!validAddressOnly || Boolean(record.address.trim())) && (!needle || [record.businessName, record.foodBusinessRegistrationNumber, record.districtName, record.address, record.assessmentResult].filter(Boolean).join(' ').toLocaleLowerCase().includes(needle))); }, [assessment, district, query, records, validAddressOnly]);
  const quality = summary?.dataQuality;
  const cards: Array<[string, string | number]> = [[text.total, summary?.totalRecords ?? records.length], [text.unique, summary?.uniqueBusinesses ?? new Set(records.map((record) => record.registrationNumberNormalized || `${record.businessNameNormalized}|${record.addressNormalized}`)).size], [text.covered, summary?.districtCount ?? districts.length], [text.categories, summary?.assessmentResultCategoryCount ?? assessments.length], [text.topDistrict, summary?.topDistrict ?? districtData[0]?.label ?? '-'], [text.registrations, summary?.recordsWithRegistrationNumbers ?? records.filter((record) => Boolean(record.registrationNumberNormalized)).length]];
  const tabs: Array<[View, string]> = [['overview', text.overview], ['districts', text.districts], ['results', text.results], ['directory', text.directory], ['quality', text.quality], ['notes', text.notes]];
  return <section className="hygiene-module"><header className="module-header hygiene-header"><p>{text.eyebrow}</p><h2>{text.title}</h2><span>{text.intro}</span></header><DisclaimerNotice>{text.disclaimer}</DisclaimerNotice><div className="green-store-tabs" role="tablist">{tabs.map(([id, label]) => <button type="button" role="tab" aria-selected={view === id} className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div>
    {view === 'overview' && <div className="green-store-view"><div className="summary-grid">{cards.map(([label, value]) => <div className="summary-tile" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="chart-grid"><article><h3>{text.districtChart}</h3><BarChart data={districtData} /></article><article><h3>{text.resultChart}</h3><BarChart data={resultData} /></article><article><h3>{text.crossChart}</h3><BarChart data={crossData} /></article></div></div>}
    {view === 'districts' && <section className="green-store-view chart-grid"><article><h3>{text.districtChart}</h3><BarChart data={districtData} /></article></section>}
    {view === 'results' && <section className="green-store-view chart-grid"><article><h3>{text.resultChart}</h3><BarChart data={resultData} /></article><article><h3>{text.crossChart}</h3><BarChart data={crossData} /></article></section>}
    {view === 'directory' && <section className="green-store-view"><div className="green-store-filters"><label className="search-field">{text.search}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text.searchPlaceholder} /></label><label>{text.district}<select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{text.allDistricts}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label>{text.assessment}<select value={assessment} onChange={(event) => setAssessment(event.target.value)}><option value="">{text.allResults}</option>{assessments.map((item) => <option key={item}>{item}</option>)}</select></label><label className="green-store-phone-toggle"><input type="checkbox" checked={validAddressOnly} onChange={(event) => setValidAddressOnly(event.target.checked)} />{text.validAddress}</label></div><p className="result-count">{filtered.length} / {records.length} {text.resultsCount}</p>{filtered.length ? <div className="green-store-table-wrap"><table className="green-store-table"><thead><tr>{[text.business, text.assessment, text.district, text.address, text.registration, text.map].map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{filtered.slice(0, 200).map((record) => <tr key={record.id}><td>{record.businessName || '-'}</td><td>{record.assessmentResult || '-'}</td><td>{record.districtName || '-'}</td><td>{record.address || '-'}</td><td>{record.foodBusinessRegistrationNumber || '-'}</td><td>{record.googleMapsQuery && <a className="green-store-map-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noopener noreferrer">{text.map}</a>}</td></tr>)}</tbody></table></div> : <p className="empty-state">{text.noResults}</p>}</section>}
    {view === 'quality' && <section className="green-store-view"><h3>{text.qualityTitle}</h3><div className="summary-grid">{[[text.duplicates, quality?.duplicateRecordCount ?? 0], [text.missingNames, quality?.missingBusinessNameCount ?? 0], [text.missingRegistrations, quality?.missingRegistrationNumberCount ?? 0], [text.missingAddresses, quality?.missingAddressCount ?? 0], [text.missingAssessments, quality?.missingAssessmentResultCount ?? 0], [text.unknownDistricts, quality?.unknownDistrictCount ?? 0], [text.unknownAssessments, quality?.unknownAssessmentValueCount ?? 0]].map(([label, value]) => <div className="summary-tile" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div></section>}
    {view === 'notes' && <section className="green-store-view data-notes"><h3>{text.notesTitle}</h3><article><h3>{text.source}</h3><p><a href={source} target="_blank" rel="noopener noreferrer">臺北市通過餐飲衛生管理分級評核業者</a>（臺北市政府衛生局）。</p></article><article><h3>{text.location}</h3><p>{text.noCoordinates}</p><p>{text.lookup}</p></article></section>}
  </section>;
}
