import { useEffect, useMemo, useState } from 'react';
import L from 'leaflet';
import 'leaflet.markercluster';
import { MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet';
import type { Language, TemporaryVendorMarketRecord } from '../types';
import { DisclaimerNotice } from './DisclaimerNotice';

const path = `${import.meta.env.BASE_URL}data/temporary-vendor-markets/records.json`;
const icon = L.divIcon({ className: 'temporary-market-marker', html: '<span>●</span>', iconSize: [26, 26], iconAnchor: [13, 13] });
const labels = (language: Language) => language === 'zh' ? {
  eyebrow: '傳統市場、攤販市集與食品採購', title: '臺北市臨時攤販集中場', intro: '以官方座標呈現的臨時攤販集中場資料；營業日與時間為來源紀錄，請於出發前確認。', search: '搜尋', district: '行政區', all: '全部', map: '地圖', records: '攤販集中場名錄', name: '管理單位', location: '範圍', day: '營業日', hours: '營業時間', open: '開啟地圖', total: '筆數', valid: '有效地圖位置', noResults: '目前篩選沒有資料', disclaimer: '本資料僅供尋找攤販集中場與食品採購地點參考，不保證目前營運、攤販出席、商品、價格、食品安全、衛生或官方推薦。', copy: '複製範圍'
} : {
  eyebrow: 'Traditional Markets, Vendor Markets & Food Shopping', title: 'Temporary Vendor Markets', intro: 'Official-coordinate records for Taipei temporary vendor markets. Operating days and hours are source records; confirm before visiting.', search: 'Search', district: 'District', all: 'All', map: 'Map', records: 'Vendor Market Directory', name: 'Managing organization', location: 'Location scope', day: 'Operating day', hours: 'Hours', open: 'Open map', total: 'Records', valid: 'Valid map locations', noResults: 'No records match the current filters', disclaimer: 'This dataset is for reference when locating vendor markets and food-shopping locations. It does not establish current operation, stall activity, products, prices, food safety, hygiene quality, or official recommendation.', copy: 'Copy location'
};

function MarketMarkers({ records }: { records: TemporaryVendorMarketRecord[] }) { const map = useMap(); useEffect(() => { const group = L.layerGroup(); records.filter((record) => record.hasValidCoordinates && record.latitude !== null && record.longitude !== null).forEach((record) => { const marker = L.marker([record.latitude!, record.longitude!], { icon }); marker.bindPopup(`<div class="popup-content"><strong>${record.operatorName || '—'}</strong><p>${record.districtName || '—'}</p><p>${record.locationScope || '—'}</p><p>${record.operatingDayRaw || '—'} · ${record.startTimeRaw || '—'}–${record.endTimeRaw || '—'}</p></div>`); group.addLayer(marker); }); map.addLayer(group); return () => { map.removeLayer(group); }; }, [map, records]); return null; }

export function TemporaryVendorMarketsModule({ language }: { language: Language }) {
  const t = labels(language); const [records, setRecords] = useState<TemporaryVendorMarketRecord[]>([]); const [query, setQuery] = useState(''); const [district, setDistrict] = useState('');
  useEffect(() => { fetch(path).then((response) => response.ok ? response.json() : []).then(setRecords).catch(() => setRecords([])); }, []);
  const districts = [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort(); const filtered = useMemo(() => records.filter((record) => (!district || record.districtName === district) && (!query || [record.operatorName, record.districtName, record.locationScope, record.operatingDayRaw].join(' ').toLowerCase().includes(query.toLowerCase()))), [district, query, records]); const valid = filtered.filter((record) => record.hasValidCoordinates && record.latitude !== null && record.longitude !== null);
  const download = () => { const header = [t.name, t.district, t.day, t.hours, t.location]; const rows = filtered.map((record) => [record.operatorName, record.districtName, record.operatingDayRaw, `${record.startTimeRaw || '—'}–${record.endTimeRaw || '—'}`, record.locationScope]); const csv = [header, ...rows].map((row) => row.map((value) => `"${String(value || '').replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: 'text/csv' })); link.download = language === 'zh' ? '臨時攤販集中場篩選資料.csv' : 'temporary-vendor-markets-filtered.csv'; link.click(); URL.revokeObjectURL(link.href); };
  return <section className="temporary-market-module"><header className="module-header"><p>{t.eyebrow}</p><h2>{t.title}</h2><span>{t.intro}</span></header><DisclaimerNotice>{t.disclaimer}</DisclaimerNotice><div className="temporary-market-filters"><label className="search-field">{t.search}<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>{t.district}<select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{t.all}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="summary-grid"><div className="summary-tile"><span>{t.total}</span><strong>{filtered.length}</strong></div><div className="summary-tile"><span>{t.valid}</span><strong>{valid.length}</strong></div></div><div className="temporary-map-panel"><MapContainer center={[25.0478, 121.5319]} zoom={12} className="commercial-map" scrollWheelZoom attributionControl={false}><TileLayer url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png" /><MarketMarkers records={valid} /></MapContainer></div><div className="temporary-actions"><button className="nearby-button" onClick={download}>CSV</button></div>{filtered.length ? <div className="green-store-table-wrap"><table className="green-store-table"><thead><tr>{[t.name, t.district, t.day, t.hours, t.location, t.open].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td>{record.operatorName || '—'}</td><td>{record.districtName || '—'}</td><td>{record.operatingDayRaw || '—'}</td><td>{record.startTimeRaw || '—'}–{record.endTimeRaw || '—'}</td><td>{record.locationScope || '—'}</td><td>{record.hasValidCoordinates ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${record.latitude},${record.longitude}`}>{t.open}</a> : '—'}</td></tr>)}</tbody></table></div> : <p className="empty-state">{t.noResults}</p>}</section>;
}
